# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'aiSocialApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Disable script sandboxing to fix the module map issues
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'NO'
      end
    end
    
    # Apply M1/M2 compatibility workaround
    if installer.respond_to?(:__apply_Xcode_12_5_M1_post_install_workaround)
      installer.__apply_Xcode_12_5_M1_post_install_workaround
    end
    
    # Fix for react-native-document-picker modulemap issue
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
    
    # Add a script phase to create empty modulemap files for problematic pods
    installer.target_installation_results.pod_target_installation_results.each do |pod_name, target_installation_result|
      if pod_name.to_s.include?('react-native-document-picker')
        target_installation_result.native_target.build_phases.each do |build_phase|
          if build_phase.display_name == "Copy Pods Resources"
            script_phase = installer.pods_project.new(Xcodeproj::Project::Object::PBXShellScriptBuildPhase)
            script_phase.name = "Create Empty Modulemap"
            script_phase.shell_script = "mkdir -p \"${PODS_CONFIGURATION_BUILD_DIR}/react-native-document-picker/\" && touch \"${PODS_CONFIGURATION_BUILD_DIR}/react-native-document-picker/react_native_document_picker.modulemap\""
            target_installation_result.native_target.build_phases.insert(0, script_phase)
            break
          end
        end
      end
    end
  end
end
